INSERT INTO Games (Name,UrlBigImage,UrlSmallImage,MinPlayer,MaxPlayer,Time,Description,"Year",Location,MinAge) VALUES
	 ('Catan','https://cf.geekdo-images.com/0XODRpReiZBFUffEcqT5-Q__original/img/oRc0AomWA9ZtFqQDZiZbIyKE1j0=/0x0/filters:format(png)/pic9156909.png','https://cf.geekdo-images.com/0XODRpReiZBFUffEcqT5-Q__small/img/SNVfF23OQafv3u8xdFolJnMkBoM=/fit-in/200x150/filters:strip_icc()/pic9156909.png',3,4,120,'In CATAN (precedentemente noto come The Settlers of Catan), i giocatori cercano di diventare la forza dominante sull''isola di Catan costruendo insediamenti, città e strade. Ad ogni turno si lanciano i dadi per determinare quali risorse produce l''isola. I giocatori costruiscono strutture “spendendo” risorse (pecore, grano, legno, mattoni e minerale) rappresentate dalle relative carte risorsa; ogni tipo di terreno, ad eccezione del deserto improduttivo, produce una risorsa specifica: le colline producono mattoni, le foreste producono legno, le montagne producono minerale, i campi producono grano e i pascoli producono pecore.
La preparazione del gioco prevede il posizionamento casuale di grandi tessere esagonali (ognuna delle quali raffigura uno dei cinque tipi di terreno che producono risorse, o il deserto) a forma di alveare e circondandole con tessere acqua, alcune delle quali contengono porti di scambio. Su ogni tessera di terreno viene posizionato un disco numerico, il cui valore corrisponderà al risultato di due dadi a sei facce. A ogni giocatore vengono assegnati due insediamenti (immaginate delle case) e delle strade (bastoncini) che vengono posizionati sugli incroci e ai confini delle tessere di terreno. I giocatori raccolgono una mano di carte risorsa in base alle tessere di terreno adiacenti all’ultimo insediamento posizionato. Una pedina ladro viene posizionata sulla tessera del deserto.
Un turno consiste nel lanciare i dadi, raccogliere carte risorsa in base al risultato del lancio e alla posizione degli insediamenti (o delle città potenziate — pensate a degli hotel), consegnare le carte risorsa (se possibile e desiderato) per ottenere miglioramenti, scambiare carte in un porto, eventualmente giocare',1995,'B.7.3',10),
	 ('Catan: Marinai','https://cf.geekdo-images.com/v8ll_1CxVGP-KN-NqkoQsg__original/img/HQqjNMRHo7Nxuoa72J5yyIq-NCY=/0x0/filters:format(jpeg)/pic8828019.jpg','https://cf.geekdo-images.com/v8ll_1CxVGP-KN-NqkoQsg__small/img/1Kuh2BgF2fqDNHijFUZHBqjKwOA=/fit-in/200x150/filters:strip_icc()/pic8828019.jpg',3,4,90,'Si tratta di un''espansione per CATAN. I giocatori possono costruire rotte marittime, molto simili alle strade. Inoltre, il gioco include numerose varianti con un numero elevato di esagoni acquatici. La versione inglese (CATAN Studio) va utilizzata esclusivamente con il gioco base inglese, anziché con quello tedesco (Kosmos), per garantire la compatibilità dei componenti. La versione tedesca Kosmos va utilizzata esclusivamente con il gioco base tedesco. Inoltre, esistono diverse edizioni; la quinta edizione è la più recente. Le edizioni devono essere utilizzate solo con la stessa edizione, altrimenti è necessario acquistare un kit di adattamento.

Parte della serie Catan (richiede CATAN)',1997,'B.7.3',10),
	 ('Mucca Pazza','https://cf.geekdo-images.com/uAi1tfvZA2TGuRJpBJUOQQ__imagepage/img/xUUUnkJVDheUwY1eRwHwQ8tvANw=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1545751.jpg','https://cf.geekdo-images.com/uAi1tfvZA2TGuRJpBJUOQQ__small/img/euPk1TaXvg-VbB5vH8cb9C_J0TY=/fit-in/200x150/filters:strip_icc()/pic1545751.jpg',2,4,15,'Dieci diversi animali provenienti dal pianeta “Kuhpiter” sono atterrati sulla Terra, ma la vacca sbadata Mucca Pazza ha premuto il pulsante sbagliato sul teletrasporto, confondendo teste, corpi e zampe di tutti gli animali e creando strane specie come il Frodrankey e l''Hocadog. I giocatori – forse nei panni di specialisti in DNA ricombinante – devono ora spostare le parti del corpo per ricreare gli animali originali, corretti e completi.

In Mucca Pazza, la testa, il corpo e le zampe di dieci animali vengono mescolati, poi posizionati sulle tre guide scorrevoli del tabellone. Dieci gettoni animale vengono posizionati a caso nella parte superiore del tabellone. In un turno, un giocatore ha a disposizione fino a tre mosse per ricreare un particolare animale; se ci riesce, prende tutti i gettoni corrispondenti sopra il tabellone, poi vengono pescati altri gettoni in modo che ce ne siano sempre dieci disponibili. Questi gettoni valgono un punto ciascuno, e chi totalizza più punti vince.

Per i giocatori più piccoli, è possibile utilizzare solo metà del tabellone, che contiene le parti di cinque animali. Con questo tabellone più piccolo, un giocatore può ricomporre qualsiasi animale con al massimo tre mosse di scorrimento, ma non diteglielo! Lasciate che siano i bambini a scoprirlo da soli...',2013,'B.5.3',4),
	 ('La corsa dei lombrichi','https://cf.geekdo-images.com/vu0tARXyCi3bxXnyQ0upsQ__original/img/yWWsk5_vCj0GPMkhlmQKNQuLMYc=/fit-in/200x150/filters:strip_icc()/pic1121031.jpg','https://cf.geekdo-images.com/vu0tARXyCi3bxXnyQ0upsQ__small/img/yWWsk5_vCj0GPMkhlmQKNQuLMYc=/fit-in/200x150/filters:strip_icc()/pic1121031.jpg',2,4,20,'Nel gioco dei dadi «Da ist der Wurm drin», i giocatori devono cercare di essere i primi a far spuntare la testa del proprio verme dal cumulo di compost in fondo al giardino.

Per preparare il tabellone, fissare un tabellone più piccolo, dotato di due fessure, a quello più grande su cui strisceranno i vermi. La prima fessura è affiancata da una fila di margherite, mentre la seconda da una fila di fragole. Ogni giocatore sceglie un colore e posiziona la testa del verme di quel colore nella traccia corrispondente sul tabellone.

Durante il proprio turno, un giocatore lancia il dado, quindi inserisce la sezione del verme del colore appropriato nella traccia che contiene il proprio verme. Le sezioni dei vermi sono disponibili in sei colori e hanno una lunghezza compresa tra 1 cm e 6 cm. In qualsiasi turno, un giocatore può posizionare la propria tessera margherita (o fragola) sopra il verme che ritiene raggiungerà per primo le margherite (o le fragole). Se quel verme fa effettivamente spuntare la testa attraverso la fessura prima di qualsiasi altro, allora quel giocatore può aggiungere la tessera margherita (o fragola) al proprio verme. (Se si sceglie male, si scarta la propria tessera.)

Vince il primo verme a sporgere la testa dal bordo più lontano del tabellone più piccolo. Per una partita più lunga, i giocatori possono far avanzare i propri vermi finché uno di essi non sporge la testa dal bordo del tabellone più grande.',2011,'B.5.3',4),
	 ('Ubongo','https://cf.geekdo-images.com/0wSuQbmk4nPwNytp9_zzPw__original/img/DccSEdsXQG65cfwPJjdrkJySojI=/0x0/filters:format(jpeg)/pic4597123.jpg','https://cf.geekdo-images.com/0wSuQbmk4nPwNytp9_zzPw__small/img/2_damZx35g1mE8kgWUpIXoHybW8=/fit-in/200x150/filters:strip_icc()/pic4597123.jpg',1,4,25,'In Ubongo, i giocatori competono per risolvere i propri puzzle il più rapidamente possibile, in modo da essere i primi a prendere le gemme disponibili. Il tabellone è composto da sei file, con dodici gemme (di vari colori) disposte su queste file. All''inizio della partita, ogni giocatore posiziona la propria pedina davanti a una di queste file. Ogni giocatore prende inoltre dodici polimini e li utilizza in ogni turno per cercare di ricreare delle figure. All''inizio di un turno, ogni giocatore riceve una carta puzzle che raffigura una forma creata da un certo numero di quadrati (un lato con 3 pezzi e l''altro con 4 pezzi). Quando tutti sono pronti, qualcuno lancia un dado per determinare quale fila di pezzi ogni giocatore può utilizzare per ricreare la forma sulla propria carta individuale. La gara è cronometrata da una clessidra e l''esito di questa gara determina l''azione sul tabellone di gioco principale. Chi risolve per primo il proprio puzzle entro il tempo stabilito può spostare la propria pedina fino a tre file a sinistra o a destra, mentre il secondo giocatore a finire si sposta di due file e il terzo giocatore di una sola fila. I giocatori raccolgono quindi due gemme dalla parte anteriore della fila in cui si trova la loro pedina, il che significa che più file riesci a muoverti, maggiore è il controllo che hai sul colore delle gemme che puoi raccogliere. Dopo aver raccolto le gemme, ogni giocatore riceve una nuova carta puzzle e inizia un nuovo round. Dopo nove turni, il gioco termina e vince chi ha raccolto il maggior numero di gemme di un unico colore! In caso di parità, i giocatori confrontano chi ha il maggior numero di gemme di un secondo colore, e così via.',2003,'B.5.3',8),
	 ('Abalone','https://cf.geekdo-images.com/UzH1jAlqYUH9VEq2Wtvzjw__original/img/pURND_gEV9F5VLeUWLqYFP3UQAQ=/0x0/filters:format(jpeg)/pic5253079.jpg','https://cf.geekdo-images.com/UzH1jAlqYUH9VEq2Wtvzjw__small/img/gWROpok8ZlqghhqoGFBFn-Znj2s=/fit-in/200x150/filters:strip_icc()/pic5253079.jpg',2,2,30,'Questo tabellone, bello e funzionale, può ospitare due squadre di biglie di grandi dimensioni. I giocatori, a turno, spingono le biglie lungo il tabellone con l''obiettivo di far uscire dal tabellone sei biglie dell''avversario. Il principio fondamentale è che una colonna di biglie ha un peso pari al numero di biglie che la compongono. Per spingere la colonna lungo quell''asse, sarà necessario spingere con un gruppo di biglie più pesante. Tuttavia, con sei direzioni possibili, è difficile difendersi alla perfezione. Inoltre, è possibile giocare con un massimo di sei giocatori acquistando set di biglie supplementari.',1987,'B.6.3',7),
	 ('Tsuro','https://cf.geekdo-images.com/2V3d4ryhxkS3RoPtDrvpUw__original/img/TP5U-O2eujPBK9IVmmifdfkWwdQ=/0x0/filters:format(jpeg)/pic875761.jpg','https://cf.geekdo-images.com/2V3d4ryhxkS3RoPtDrvpUw__small/img/NWgNhoxUIF7Lmj1apRkZQhFL6NU=/fit-in/200x150/filters:strip_icc()/pic875761.jpg',2,5,20,'Tsuro è un gioco meravigliosamente semplice in cui, ad ogni turno, si posiziona una tessera davanti alla propria pedina per prolungarne il percorso. L''obiettivo è mantenere la propria pedina sul tabellone più a lungo di quella di chiunque altro, ma man mano che il tabellone si riempie ciò diventa più difficile perché rimangono meno spazi liberi e la tessera di un altro giocatore potrebbe anche prolungare il proprio percorso in una direzione che si preferirebbe evitare. Tsuro ha un tema spirituale asiatico: le linee rappresentano le “molte strade che conducono alla saggezza divina” e il gioco nel suo insieme rappresenta “la classica ricerca dell''illuminazione”. Questo tema è molto leggero e il gioco si svolge essenzialmente come un gioco di strategia astratto. Il gioco consiste in tessere con linee sinuose, una griglia 6x6 su cui posare queste tessere e un segnalino per ogni giocatore. Ogni giocatore ha una mano di tessere. Nel proprio turno si fanno due cose: si posiziona una tessera dalla propria mano sul tabellone accanto al proprio segnalino e si sposta il segnalino il più lontano possibile lungo la linea su cui si trova attualmente, finché non viene fermato da uno spazio vuoto in cui non c''è (ancora) una tessera, dal bordo del tabellone o dalla collisione con il segnalino di un altro giocatore. Se il proprio segnalino raggiunge il bordo del tabellone o entra in collisione con il segnalino di un altro giocatore, si è fuori dal gioco. Lo scopo del gioco è essere l''ultimo giocatore rimasto con una pedina sul tabellone. La strategia consiste quindi nel cercare di spingere i tuoi avversari l''uno contro l''altro o fuori dal tabellone, estendendo al contempo il tuo percorso in direzioni che rendano difficile ai tuoi avversari fare lo stesso.',2005,'B.6.3',8),
	 ('Super Farmer','https://cf.geekdo-images.com/sl3RyQXqa39pcJyQdA0jyg__original/img/JEQ34OH9NLAxD9CtkjhZAkjB1Lc=/0x0/filters:format(jpeg)/pic1802593.jpg','https://cf.geekdo-images.com/sl3RyQXqa39pcJyQdA0jyg__small/img/7CJLU1oGaOdnHuHl8yvo0yZdLTg=/fit-in/200x150/filters:strip_icc()/pic1802593.jpg',2,6,20,'Ogni giocatore assume il ruolo del proprietario di una fattoria di animali. L''obiettivo principale è allevare, scambiare e raccogliere animali diversi; vince chi riesce a raccogliere almeno un esemplare di ogni specie. Ma attenzione: ci sono volpi in giro che cercano di rubarti i conigli e lupi che possono divorare tutti gli altri tuoi animali.',1943,'B.6.3',7),
	 ('Azul','https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__original/img/AkbtYVc6xXJF3c9EUrakklcclKw=/0x0/filters:format(png)/pic6973671.png','https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__small/img/ccsXKrdGJw-YSClWwzVUwk5Nh9Y=/fit-in/200x150/filters:strip_icc()/pic6973671.png',2,4,45,'Introdotti dai Mori, gli azulejos (originariamente piastrelle in ceramica bianche e blu) furono pienamente adottati dai portoghesi quando il loro re Manuel I, durante una visita al palazzo dell’Alhambra nel sud della Spagna, rimase incantato dalla straordinaria bellezza delle piastrelle decorative moresche. Il re, sbalordito dalla bellezza degli interni dell''Alhambra, ordinò immediatamente che il proprio palazzo in Portogallo fosse decorato con piastrelle simili. Nei panni di un artista posatore di piastrelle, ti viene chiesto di abbellire le pareti del Palazzo Reale di Évora.

Nel gioco Azul, i giocatori, a turno, scelgono tessere colorate dai fornitori e le aggiungono al proprio tabellone. Più avanti nel turno, i giocatori ottengono punti in base a come hanno posizionato le tessere per decorare il palazzo. Si ottengono punti extra per schemi specifici e per il completamento di serie; le risorse sprecate penalizzano il punteggio del giocatore. Vince il giocatore con il maggior numero di punti alla fine del gioco.',2017,'B.6.3',8),
	 ('Caduta Libera','https://cf.geekdo-images.com/DkFGsTEyBIAcwusadROixg__original/img/K-A72FllxrXQK5gaZIswOaVKoys=/0x0/filters:format(jpeg)/pic3918132.jpg','https://cf.geekdo-images.com/DkFGsTEyBIAcwusadROixg__small/img/s5gq6Hr40hir6Jc1xAwhbLMwdPE=/fit-in/200x150/filters:strip_icc()/pic3918132.jpg',2,4,30,'Rispondi correttamente a tutte le domande per aumentare le tue possibilità di vincere il più possibile. In questo gioco, ogni volta che qualcuno sbaglia, vince un altro giocatore.

Ogni partita è composta da 10 round: alla fine di ogni round, viene assegnata una somma di denaro al giocatore che riesce a far cadere il proprio avversario. Il giocatore con più soldi alla fine della partita sarà il vincitore.',2015,'B.6.3',10);

INSERT INTO Games (Name,UrlBigImage,UrlSmallImage,MinPlayer,MaxPlayer,Time,Description,"Year",Location,MinAge) VALUES
	 ('Ticket to Ride','https://cf.geekdo-images.com/kdWYkW-7AqG63HhqPL6ekA__original/img/rWF8r4JXXCQQ7QhiWHhmT-rQ3Pc=/0x0/filters:format(jpeg)/pic8937637.jpg','https://cf.geekdo-images.com/kdWYkW-7AqG63HhqPL6ekA__small/img/5G46jv8MFh_BfX67iMSouTMhKxc=/fit-in/200x150/filters:strip_icc()/pic8937637.jpg',2,5,60,'Grazie a un regolamento elegante e semplice, Ticket to Ride si impara in meno di 15 minuti. I giocatori raccolgono carte raffiguranti vari tipi di vagoni ferroviari, che utilizzano poi per occupare tratte ferroviarie in Nord America. Più lunghe sono le tratte, più punti si guadagnano. Si ottengono punti aggiuntivi completando i Biglietti Destinazione – carte obiettivo che collegano città lontane – e per il giocatore che costruisce la tratta continua più lunga.',2004,'B.6.3',8),
	 ('Ticket to Ride: USA 1910	2	5	60	8	2006	B.1.1	https://cf.geekdo-images.com/JMC_eP625nO1t_uI9HoQ7g__original/img/j7HTQ3Ijy8mr9kYsY9nZ5WLt26I=/0x0/filters:format(jpeg)/pic144599.jpg	https://cf.geekdo-images.com/JMC_eP625nO1t_uI9HoQ7g__small/img/3_K2lD007FGiRNsD7qvhOXO1roM=/fit-in/200x150/filters:strip_icc()/pic144599.jpg	"Ticket to Ride: USA 1910 è un''espansione di carte per il gioco da tavolo originale Ticket to Ride, vincitore dello Spiel des Jahres 2004. Contiene 181 carte di grande formato (delle stesse dimensioni di quelle di Ticket to Ride: Europe e Ticket to Ride: Märklin).  Include 35 nuovi biglietti destinazione del 1910, una carta bonus GlobeTrotter per chi completa il maggior numero di biglietti, 4 biglietti destinazione del treno misterioso originariamente forniti nell''espansione Ticket to Ride: Mystery Train, e un mazzo completo sostitutivo delle 141 carte del mazzo originale del gioco (30 biglietti destinazione (4 carte hanno un valore ridotto rispetto a Ticket to Ride), 110 carte Treno e 1 carta Bonus Percorso più lungo (Trans America Express)).

Il regolamento è stato redatto dal designer originale del gioco, Alan R. Moon, e offre tre diverse modalità di gioco aggiuntive:

     Le Regole del 1910: Si gioca come nel Ticket to Ride standard, ma utilizzando solo i biglietti di destinazione del 1910 e la carta Bonus GlobeTrotter.
     Le regole delle grandi città: si gioca utilizzando solo i 35 biglietti di destinazione “grandi città” appena identificati (15 biglietti standard, 19 biglietti del 1910 e 1 biglietto treno misterioso).
     Il Mega Gioco: include tutti i biglietti di destinazione e le carte bonus del gioco (30 biglietti standard, 35 biglietti del 1910, 4 biglietti treno misteriosi ed entrambe le carte bonus).


Parte della serie Ticket to Ride."','https://cf.geekdo-images.com/JMC_eP625nO1t_uI9HoQ7g__original/img/j7HTQ3Ijy8mr9kYsY9nZ5WLt26I=/0x0/filters:format(jpeg)/pic144599.jpg','https://cf.geekdo-images.com/JMC_eP625nO1t_uI9HoQ7g__small/img/3_K2lD007FGiRNsD7qvhOXO1roM=/fit-in/200x150/filters:strip_icc()/pic144599.jpg',2,5,60,'Ticket to Ride: USA 1910 è un''espansione di carte per il gioco da tavolo originale Ticket to Ride, vincitore dello Spiel des Jahres 2004. Contiene 181 carte di grande formato (delle stesse dimensioni di quelle di Ticket to Ride: Europe e Ticket to Ride: Märklin).  Include 35 nuovi biglietti destinazione del 1910, una carta bonus GlobeTrotter per chi completa il maggior numero di biglietti, 4 biglietti destinazione del treno misterioso originariamente forniti nell''espansione Ticket to Ride: Mystery Train, e un mazzo completo sostitutivo delle 141 carte del mazzo originale del gioco (30 biglietti destinazione (4 carte hanno un valore ridotto rispetto a Ticket to Ride), 110 carte Treno e 1 carta Bonus Percorso più lungo (Trans America Express)).

Il regolamento è stato redatto dal designer originale del gioco, Alan R. Moon, e offre tre diverse modalità di gioco aggiuntive:

     Le Regole del 1910: Si gioca come nel Ticket to Ride standard, ma utilizzando solo i biglietti di destinazione del 1910 e la carta Bonus GlobeTrotter.
     Le regole delle grandi città: si gioca utilizzando solo i 35 biglietti di destinazione “grandi città” appena identificati (15 biglietti standard, 19 biglietti del 1910 e 1 biglietto treno misterioso).
     Il Mega Gioco: include tutti i biglietti di destinazione e le carte bonus del gioco (30 biglietti standard, 35 biglietti del 1910, 4 biglietti treno misteriosi ed entrambe le carte bonus).


Parte della serie Ticket to Ride.',2006,'B.1.1',8),
	 ('Le Leggende di Andor','https://cf.geekdo-images.com/IO8_BYKeofnWy8DIjo2RRg__original/img/GEmDZyN1Q9Jlv88QvOF58N7yBIo=/0x0/filters:format(jpeg)/pic2606106.jpg','https://cf.geekdo-images.com/IO8_BYKeofnWy8DIjo2RRg__small/img/pMbV-KGyO3D9U6hnBzNRfylZvto=/fit-in/200x150/filters:strip_icc()/pic2606106.jpg',2,4,90,'Legends of Andor è un gioco da tavolo cooperativo di avventura per due-quattro giocatori in cui un gruppo di eroi deve collaborare per difendere un regno fantastico dalle orde invasori. Per proteggere i confini di Andor, gli eroi intraprenderanno missioni pericolose nel corso di cinque scenari unici (oltre a uno scenario finale creato dagli stessi giocatori). Ma poiché l''ingegnoso sistema di gioco mantiene le creature in marcia verso il castello, i giocatori devono bilanciare attentamente le loro priorità.

Il cuore di Legends of Andor è la sua narrativa unica, i cui scenari collegati raccontano una storia generale man mano che i giocatori completano con successo gli obiettivi. Per ogni scenario, o “Leggenda”, un mazzo di leggende trasmette la trama di una storia in continuo sviluppo... una storia in cui i giocatori sono i protagonisti. Un segnalino di legno si sposta lungo la traccia delle leggende sul tabellone in punti chiave durante ogni scenario, innescando la pesca di una nuova carta leggenda, l''introduzione di nuovi effetti che alterano il gioco e l''avanzamento della trama della storia. Alla fine, i giocatori devono sforzarsi di guidare il destino di Andor attraverso le loro azioni eroiche, portando a un lieto fine la loro epica storia fantasy.

I loro eroi vagheranno per la terra completando missioni in nome della gloria, o si dedicheranno alla difesa del regno? Scopri epiche storie di gloria mentre vivi le Leggende di Andor!

descrizione dell''editore',2012,'B.6.3',10),
	 ('Raccontami una Storia: Fiabe','https://cf.geekdo-images.com/g7SMu5FUdFYBvu_pSRSsHA__original/img/oxffhaLSxWrF_hgygnurdZHnwO8=/0x0/filters:format(jpeg)/pic2904481.jpg','https://cf.geekdo-images.com/g7SMu5FUdFYBvu_pSRSsHA__small/img/YgjGz3Dt1kQ8sxF9gCqGjINEALE=/fit-in/200x150/filters:strip_icc()/pic2904481.jpg',3,8,30,'Descrizione dell''editore:

Le quattro parole «C''era una volta» hanno un potere straordinario. Annunciano avventure, magia, creature incantate e misteriose trasformazioni. Evocano terre lontane, coraggiosi cacciatori, principesse determinate, giganti temibili e animali parlanti. Ma soprattutto, danno inizio alle nostre fiabe preferite.

Fairy Tales, il gioco di debutto della serie StoryLine, vi invita a creare le vostre fiabe originali iniziando con quella straordinaria frase “C''era una volta”. In questo fantasioso gioco di carte, da tre a otto giocatori creano insieme una storia, con ogni giocatore che contribuisce alla narrazione con personaggi, luoghi, oggetti ed eventi.

StoryLine: Fairy Tales è un gioco collaborativo di narrazione che incoraggia i giocatori a giocare le carte per arricchire la storia e abbellirla. In ogni round un giocatore fa da narratore e chiede agli altri giocatori un tipo specifico di carta, come un oggetto o un luogo, da aggiungere alla storia. Tutti gli altri giocatori scelgono una di queste carte dalla propria mano, poi il narratore sceglie quella che gli piace di più e assegna un punto a quel giocatore. Alla fine della storia, vince chi ha totalizzato il maggior numero di punti.',2016,'B.6.3',8),
	 ('Mariposas','https://cf.geekdo-images.com/UHTHsuI998L89uSTXS3hxg__original/img/OMzfKuv9bpTVIT5KBZcnMfm3Jmg=/0x0/filters:format(jpeg)/pic5153415.jpg','https://cf.geekdo-images.com/UHTHsuI998L89uSTXS3hxg__small/img/ruD8L6-y9vFuuvYd1eABXJPnsXk=/fit-in/200x150/filters:strip_icc()/pic5153415.jpg',2,5,75,'Ogni primavera, milioni di farfalle monarca lasciano il Messico per diffondersi in tutto il Nord America orientale. Ogni autunno, milioni di esemplari tornano in Messico. Tuttavia, nessuna farfalla compie mai l''intero viaggio di andata e ritorno.

Mariposas è un gioco di movimento e raccolta di set che permette ai giocatori di partecipare a questo incredibile viaggio.

Mariposas si gioca in tre stagioni. In generale, le tue farfalle cercano di dirigersi a nord in primavera, sparpagliarsi in estate e tornare a sud in autunno. La fine di ogni stagione porta a un round di punteggio e, alla fine dell''autunno, il giocatore con la famiglia di farfalle di maggior successo — ovvero, il maggior numero di punti vittoria — vince la partita.

—descrizione dell''editore',2020,'B.6.3',14),
	 ('Tokyo Highway','https://cf.geekdo-images.com/fV_nbXzF2NEcCpDbyIfkBg__original/img/qdgyMhDfwNN9bkDry76Juv-5_pk=/0x0/filters:format(jpeg)/pic4331609.jpg','https://cf.geekdo-images.com/fV_nbXzF2NEcCpDbyIfkBg__small/img/5CImncZI1a3Ost0FQl23lEXy6Gc=/fit-in/200x150/filters:strip_icc()/pic4331609.jpg',2,4,30,'In Tokyo Highway, i giocatori competono per essere i primi a posizionare tutte le loro auto sulla strada — ma per farlo devono costruire le carreggiate in modo che le loro auto abbiano un percorso da seguire!

Nel corso del gioco, i giocatori costruiscono colonne di varie altezze utilizzando gli 88 pilastri grigi e gialli contenuti nella scatola, quindi collegano tali colonne con dei bastoncini che fungono da carreggiate; solitamente, la colonna che si crea non ha la stessa altezza di quella a cui è collegata. Quando si posiziona un''autostrada che passa sotto o sopra un''autostrada esistente, si può (con attenzione!) posizionare un''auto su quell''autostrada. Posizionate un''autostrada che passa sia sopra che sotto altre autostrade e potrete posizionare due auto!

I cilindri gialli vi consentono di creare una colonna della stessa altezza di un''altra, permettendovi al contempo di biforcare la carreggiata per creare più curve e tornanti.

Il primo giocatore a posizionare tutte e dieci le proprie auto — con o senza l''uso delle pinzette — vince!

Questa versione di Tokyo Highway include sia il gioco base originale che l''espansione che consente di giocare con un massimo di quattro giocatori — per non parlare dei quattro edifici che aggiungono ulteriori ostacoli mentre si cerca di stendere il cemento.',2018,'B.7.3',8),
	 ('Carcassonne','https://cf.geekdo-images.com/peUgu3A20LRmAXAMyDQfpQ__original/img/bP18m_PYjyFOv1IBGgMOteQUneA=/0x0/filters:format(jpeg)/pic8621446.jpg','https://cf.geekdo-images.com/peUgu3A20LRmAXAMyDQfpQ__small/img/oEEslN-EGqh82sNI6Aj4_MFXYg0=/fit-in/200x150/filters:strip_icc()/pic8621446.jpg',2,5,45,'Carcassonne è un gioco di posizionamento di tessere in cui i giocatori pescano e posizionano una tessera su cui è raffigurato un paesaggio del sud della Francia. La tessera può raffigurare una città, una strada, un chiostro, una prateria o una combinazione di questi elementi, e deve essere posizionata in modo adiacente alle tessere già giocate, in modo tale che le città siano collegate alle città, le strade alle strade e così via. Dopo aver posizionato una tessera, il giocatore può decidere di collocare uno dei propri meeples in una delle aree su di essa raffigurate: nella città come cavaliere, sulla strada come brigante, nel chiostro come monaco o nel campo come contadino. Quando quell''area è completa, quel meeple fa guadagnare punti al suo proprietario.

Durante una partita a Carcassonne, i giocatori si trovano di fronte a decisioni del tipo: “Vale davvero la pena mettere lì il mio ultimo meeples?” oppure “Dovrei usare questa tessera per espandere la mia città, o dovrei invece posizionarla vicino al mio avversario, rendendo così più difficile per lui completarla e guadagnare punti?” Poiché i giocatori posizionano solo una tessera e hanno la possibilità di posizionare un meeples su di essa, i turni procedono rapidamente anche se si tratta di un gioco ricco di opzioni e possibilità.

Prima gioco della serie Carcassonne.',2000,'B.7.3',7),
	 ('Carcassonne Big Box','https://cf.geekdo-images.com/TgEsqu_BQ7bbt9Zb556STQ__original/img/XcxA99i7CcPljIbcuHeOE-zUlgI=/0x0/filters:format(jpeg)/pic201589.jpg','https://cf.geekdo-images.com/TgEsqu_BQ7bbt9Zb556STQ__small/img/ulHQGla8uCWTmaLW9TaEXkp5-4I=/fit-in/200x150/filters:strip_icc()/pic201589.jpg',2,6,45,'Carcassonne è un gioco di posizionamento di tessere in cui i giocatori pescano e posizionano una tessera raffigurante un paesaggio del sud della Francia. La tessera può raffigurare una città, una strada, un chiostro, una prateria o una combinazione di questi elementi, e deve essere posizionata in modo adiacente alle tessere già giocate, in modo tale che le città siano collegate alle città, le strade alle strade e così via. Dopo aver posizionato una tessera, il giocatore può decidere di collocare uno dei suoi meeples su una delle aree raffigurate: sulla città come cavaliere, sulla strada come brigante, sul chiostro come monaco o sul prato come contadino. Quando quell''area è completa, quel meeple fa guadagnare punti al suo proprietario.

Durante una partita a Carcassonne, i giocatori si trovano di fronte a decisioni del tipo: “Vale davvero la pena mettere lì il mio ultimo meeple?” oppure “Dovrei usare questa tessera per espandere la mia città, o dovrei invece posizionarla vicino al mio avversario, rendendogli difficile completare il suo progetto e guadagnare punti?” Dato che i giocatori posizionano solo una tessera e hanno la possibilità di metterci sopra un meeple, i turni procedono rapidamente anche se si tratta di un gioco ricco di opzioni e possibilità.

Questa confezione grande include il gioco base, Cathedrals, Traders, Builders, Princess Dragon e The Tower. La versione inglese include anche The River.',2006,'B.7.3',7),
	 ('Carcassonne: Locande e Cattedrali (1)','https://cf.geekdo-images.com/9W3DkpIZwD-CrQrzfewG1Q__original/img/ukfywreE-NImHPVgXtXbUCyLGXA=/0x0/filters:format(jpeg)/pic9210962.jpg','https://cf.geekdo-images.com/9W3DkpIZwD-CrQrzfewG1Q__small/img/1PH0tUSpC04Gdfpv40r5jC-PP_8=/fit-in/200x150/filters:strip_icc()/pic9210962.jpg',2,6,60,'Carcassonne: Die Erweiterung (nelle edizioni successive il titolo è stato modificato in Inns &amp; Cathedrals) è la prima grande espansione di Carcassonne e introduce alcuni nuovi elementi nel gioco.  Sono presenti due tipi di tessere completamente nuovi: le locande e le cattedrali.  Ci sono anche nuove tessere che raffigurano città, strade e chiostri in forme diverse.  Inoltre, ogni giocatore riceve un “meeple grande” che vale come due meeples normali.  Un altro set completo di meeples permette ora a 6 giocatori di divertirsi con il gioco.  Infine, un set di carte punteggio aiuta a rendere il conteggio dei punti un po'' più chiaro.

Parte della serie Carcassonne.',2002,'B.7.3',8),
	 ('Carcassonne: La Principessa e il Drago (3)','https://cf.geekdo-images.com/qqsCzGyFGZVGklj3q5jNkQ__original/img/2FQbC3UupAVOdYmD2Iq-XSE7grY=/0x0/filters:format(jpeg)/pic9210965.jpg','https://cf.geekdo-images.com/qqsCzGyFGZVGklj3q5jNkQ__small/img/SLazAP_VduRWc12OPSLyXGeq4rc=/fit-in/200x150/filters:strip_icc()/pic9210965.jpg',2,6,60,'In questa terza grande espansione del pluripremiato Carcassonne, ci addentriamo nel regno della fantasia.
Le terre intorno a Carcassonne sono state invase da un drago, che rende la vita molto difficile agli abitanti. Coraggiosi eroi si avventurano per affrontare il pericolo, ma senza l''aiuto delle fate le loro possibilità di successo sono scarse.
In città, la principessa chiede aiuto ai cavalieri, mentre i contadini costruiscono passaggi segreti per muoversi senza essere scoperti dal drago.

Contenuto: 30 nuove tessere con nidi di drago, vulcani, porte magiche e principesse; 1 grande drago in legno; 1 fata in legno. Contrariamente a quanto riportato in precedenza, in “La principessa e il drago” non sono presenti miniature di principesse.

Parte della serie Carcassonne.',2005,'B.7.3',13);